// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aaa.Data;

namespace aaa.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220608125842_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("aaa.Models.AttestionDeCesseison", b =>
                {
                    b.Property<int>("AttestionDeCesseisonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DossierId")
                        .HasColumnType("int");

                    b.Property<decimal>("NDassurance")
                        .HasColumnType("numeric(12)");

                    b.Property<string>("Nom_ET_Prenom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RaisonSociale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AttestionDeCesseisonId");

                    b.HasIndex("DossierId");

                    b.ToTable("AttestionDeCesseison", "dbo");
                });

            modelBuilder.Entity("aaa.Models.AttestionDeSalaire", b =>
                {
                    b.Property<int>("AttestionDeSalaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttestionDeSalaireAnnee")
                        .HasColumnType("int");

                    b.Property<string>("DesiguationDeLaClasseDallocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DossierId")
                        .HasColumnType("int");

                    b.Property<string>("DuréeDuTravail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DésignationDeLemploi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Périondes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SalaireSoumisRetenue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AttestionDeSalaireId");

                    b.HasIndex("DossierId");

                    b.ToTable("AttestionDeSalaires");
                });

            modelBuilder.Entity("aaa.Models.AttestionTravail", b =>
                {
                    b.Property<int>("AttestionTravailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DossierId")
                        .HasColumnType("int");

                    b.Property<string>("PeriodeReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SalaireSoumisCotisation")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AttestionTravailId");

                    b.HasIndex("DossierId");

                    b.ToTable("AttestionTravails");
                });

            modelBuilder.Entity("aaa.Models.Dossier", b =>
                {
                    b.Property<int>("DossierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeteNaissance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DubutTravail")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("EmployeePrenom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Etat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinTravail")
                        .HasColumnType("datetime2");

                    b.Property<string>("NaissanceWilaya")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeParronPere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeParronmere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroAllocationAssure")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("NumeroAllocationFamilailes")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("NumeroSocialesAssure")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("NumeroSocialesFamilailes")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("PrenomParronPere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrenomParronmere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DossierId");

                    b.ToTable("dossiers");
                });

            modelBuilder.Entity("aaa.Models.AttestionDeCesseison", b =>
                {
                    b.HasOne("aaa.Models.Dossier", "Dossier")
                        .WithMany("AttestionDeCesseisons")
                        .HasForeignKey("DossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("aaa.Models.AttestionDeSalaire", b =>
                {
                    b.HasOne("aaa.Models.Dossier", "Employee")
                        .WithMany("AttestionDeSalaires")
                        .HasForeignKey("DossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("aaa.Models.AttestionTravail", b =>
                {
                    b.HasOne("aaa.Models.Dossier", "Dossier")
                        .WithMany("AttestionTravails")
                        .HasForeignKey("DossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");
                });

            modelBuilder.Entity("aaa.Models.Dossier", b =>
                {
                    b.Navigation("AttestionDeCesseisons");

                    b.Navigation("AttestionDeSalaires");

                    b.Navigation("AttestionTravails");
                });
#pragma warning restore 612, 618
        }
    }
}
